name: Test Feature-Branch
# dev 브랜치로 PR 보내면 유닛 테스트

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node v16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies 🛠
        run: yarn install

      - name: Unit Testing 🧪
        run: yarn test:unit --passWithNoTests
